import {
    addNewProfile,
    NEW_PROFILE,
    UPDATE_USERINFO,
    getProfilePicture,
    getUserInfo,
    GET_USERINFO,
} from "./userActions";
import {
    SIGNIN,
    SIGNOUT,
    ERROR_SIGNIN,
    signin,
    signout,
    clearError,
    CLEAR_ERROR,
    SYNC_START,
    syncData,
    syncComplete,
    SYNC_COMPLETE,
} from "./authActions";
import {
    PATIENT_ERROR,
    GET_PATIENTS_LIST,
    getPatientsList,
    GET_PATIENT_DETAIL,
    getPatientDetail,
    GET_PROGRESS_NOTES,
    getProgressNotes,
    INFORMATION_EXISTS,
    ADD_PROGRESS_NOTES,
    postProgressNotes,
    storeFileInMemory,
    PATIENT_CHART_PATH,
    PATIENT_DETAIL_LOAD_OFFLINE,
    PROGRESS_NOTES_LOAD_OFFLINE,
    loadPatientDataInReduxFromPouchDB,
    SAVE_NOTES_OFFLINE,
    notesStoreOffline,
    postOfflineNotes,
    POST_OFFLINE_NOTE,
} from "./patientActions";
import {
    GET_VISITS_LIST,
    getVisitsList,
    GET_VISIT_DETAIL,
    getVisitDetails,
    VISIT_ACTIONS_ERROR,
    ADD_VISIT_ADDRESS,
    getPatientDetailInBulk,
    VISIT_UPDATE_STATUS,
    updateVisitStatus,
    PROGRESS_NOTES_OFFLINE_SUCCESS,
    PATIENT_DETAIL_OFFLINE_SUCCESS,
} from "./visitActions";
import {
    NET_STATUS,
    checkNetStatus,
    // offlineLogin,
    OFFLINE_LOGIN,
    OFFLINE_VISITS,
    OFFLINE_PATIENTS,
} from "./offlineActions";

export const actions = {
    NEW_PROFILE,
    UPDATE_USERINFO,
    SIGNOUT,
    SIGNIN,
    ERROR_SIGNIN,
    OFFLINE_LOGIN,
    GET_PATIENTS_LIST,
    NET_STATUS,
    CLEAR_ERROR,
    GET_USERINFO,
    GET_PATIENT_DETAIL,
    PATIENT_ERROR,
    GET_PROGRESS_NOTES,
    GET_VISITS_LIST,
    VISIT_ACTIONS_ERROR,
    GET_VISIT_DETAIL,
    INFORMATION_EXISTS,
    ADD_PROGRESS_NOTES,
    ADD_VISIT_ADDRESS,
    OFFLINE_VISITS,
    OFFLINE_PATIENTS,
    PATIENT_CHART_PATH,
    PATIENT_DETAIL_LOAD_OFFLINE,
    PROGRESS_NOTES_LOAD_OFFLINE,
    VISIT_UPDATE_STATUS,
    SAVE_NOTES_OFFLINE,
    POST_OFFLINE_NOTE,
    PROGRESS_NOTES_OFFLINE_SUCCESS,
    PATIENT_DETAIL_OFFLINE_SUCCESS,
    SYNC_START,
    SYNC_COMPLETE,
};

export const ACs = {
    addNewProfile,
    signout,
    signin,
    // offlineLogin,
    getPatientsList,
    checkNetStatus,
    getProfilePicture,
    clearError,
    getUserInfo,
    getPatientDetail,
    getProgressNotes,
    getVisitsList,
    getVisitDetails,
    postProgressNotes,
    getPatientDetailInBulk,
    storeFileInMemory,
    loadPatientDataInReduxFromPouchDB,
    updateVisitStatus,
    notesStoreOffline,
    postOfflineNotes,
    syncData,
    syncComplete,
};
